In [1]:
import numpy as np

In [3]:
arr = np.array([[1, 2, 3], [4, 5, 6]])
arr

array([[1, 2, 3],
       [4, 5, 6]])

In [5]:
arr = np.array([np.arange(0, 11, 2), np.arange(10, 21, 2)])

In [7]:
print(arr)

[[ 0  2  4  6  8 10]
 [10 12 14 16 18 20]]


In [22]:
arr = np.array([1, 5, 14])
bins = np.array([1, 4, 7, 15])
inds = np.digitize(arr, bins)

In [23]:
print(inds)

[1 2 3]


In [25]:
arr = np.array([[1, 3, 5], [5, 7, 8]])
bins = np.array([[1, 5, 10], [5, 7, 9]])
inds =  np.digitize(arr, bins)

ValueError: object too deep for desired array

In [26]:
state = [1, 2]
tuple(state)

(1, 2)